

/** 平台列表 */
export const LIST_ICONS = [
  {"name": "其他", "logourl": "", "color": "#8B4513"},
  {"name": "微信", "logourl": "", "color": "#228B22"},
  {"name": "QQ", "logourl": "", "color": "#1E90FF"},
  {"name": "微博", "logourl": "", "color": "#FF4500"},
  {"name": "探探", "logourl": "", "color": "#FF1493"},
  {"name": "奢途", "logourl": "", "color": "#8A2BE2"},
  {"name": "淘宝", "logourl": "", "color": "#FF8C00"},
  {"name": "京东", "logourl": "", "color": "#DC143C"},
  {"name": "拼多多", "logourl": "", "color": "#32CD32"},
  {"name": "苏宁易购", "logourl": "", "color": "#00CED1"},
  {"name": "唯品会", "logourl": "", "color": "#FF69B4"},
  {"name": "小红书", "logourl": "", "color": "#FF6347"},
  {"name": "蘑菇街", "logourl": "", "color": "#7B68EE"},
  {"name": "聚美优品", "logourl": "", "color": "#20B2AA"},
  {"name": "咕哇找搭子小程序", "logourl": "", "color": "#FF7F50"},
  {"name": "陌陌", "logourl": "", "color": "#6A5ACD"},
  {"name": "Soul", "logourl": "", "color": "#FF4500"},
  {"name": "他趣", "logourl": "", "color": "#8B008B"},
  {"name": "YO 语音", "logourl": "", "color": "#2E8B57"},
  {"name": "丛丛小程序", "logourl": "", "color": "#9932CC"},
  {"name": "支付宝", "logourl": "", "color": "#00BFFF"},
  {"name": "滴滴出行", "logourl": "", "color": "#FFD700"},
  {"name": "携程", "logourl": "", "color": "#BA55D3"},
  {"name": "腾讯视频", "logourl": "", "color": "#3CB371"},
  {"name": "爱奇艺", "logourl": "", "color": "#FF4500"},
  {"name": "芒果 TV", "logourl": "", "color": "#FF8C00"},
  {"name": "优酷视频", "logourl": "", "color": "#32CD32"},
  {"name": "哔哩哔哩", "logourl": "", "color": "#00BFFF"},
  {"name": "今日头条", "logourl": "", "color": "#FF6347"},
  {"name": "抖音火山版", "logourl": "", "color": "#FF1493"},
  {"name": "西瓜视频", "logourl": "", "color": "#20B2AA"},
  {"name": "懂车帝", "logourl": "", "color": "#8A2BE2"},
  {"name": "皮皮虾", "logourl": "", "color": "#FF7F50"},
  {"name": "飞书", "logourl": "", "color": "#6A5ACD"},
  {"name": "网易云音乐", "logourl": "", "color": "#DC143C"},
  {"name": "酷狗音乐", "logourl": "", "color": "#00CED1"},
  {"name": "QQ 音乐", "logourl": "", "color": "#FF69B4"},
  {"name": "全民 K 歌", "logourl": "", "color": "#7B68EE"},
  {"name": "喜马拉雅 FM", "logourl": "", "color": "#FF4500"},
  {"name": "蜻蜓 FM", "logourl": "", "color": "#8B008B"},
  {"name": "荔枝 FM", "logourl": "", "color": "#2E8B57"},
  {"name": "作业帮", "logourl": "", "color": "#9932CC"},
  {"name": "猿辅导", "logourl": "", "color": "#00BFFF"},
  {"name": "百度文库", "logourl": "", "color": "#FFD700"},
  {"name": "豆丁网", "logourl": "", "color": "#BA55D3"},
  {"name": "知乎", "logourl": "", "color": "#3CB371"},
  {"name": "CSDN", "logourl": "", "color": "#FF4500"},
  {"name": "脉脉", "logourl": "", "color": "#FF8C00"},
  {"name": "BOSS 直聘", "logourl": "", "color": "#32CD32"},
  {"name": "智联招聘", "logourl": "", "color": "#00BFFF"},
  {"name": "58 同城", "logourl": "", "color": "#FF6347"},
  {"name": "赶集网", "logourl": "", "color": "#FF1493"},
  {"name": "闲鱼", "logourl": "", "color": "#20B2AA"},
  {"name": "转转", "logourl": "", "color": "#8A2BE2"},
  {"name": "饿了么", "logourl": "", "color": "#FF7F50"},
  {"name": "大众点评", "logourl": "", "color": "#6A5ACD"},
  {"name": "腾讯新闻", "logourl": "", "color": "#DC143C"},
  {"name": "澎湃新闻", "logourl": "", "color": "#00CED1"},
  {"name": "虎扑", "logourl": "", "color": "#FF69B4"},
  {"name": "雪球", "logourl": "", "color": "#7B68EE"},
  {"name": "同花顺", "logourl": "", "color": "#FF4500"}
]

/** 本地存储主密码的key */
export const STORAGE_KEY_FOR_SESSION = 'STORAGE_KEY_FOR_SESSION'

